[package]
name = "weapons"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.209", features = ["derive"] }
surrealdb = "2.0.4"
thiserror = "1.0.64"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
chrono = "0.4.38"
